version: '3.1'
services:
  sphereserver:
    image: sphereserver
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    build: sphereserver/Dockerfile
    volumes:
      - ${ULTIMA_MUL_PATH}:/sphereserver/mul:ro
      - ./accounts:/sphereserver/accounts:rw
      - ./save:/sphereserver/save:rw
    ports:
      - 2593:2593
    environment:
      - HOSTNAME=192.168.0.1
      - SHARDNAME="This Shard's Name"
